### ISSUE TITLE
Laços de repetição

### ISSUE THREAD

**Issue by karinaizo** [GurgelAmaral/AVALIACAO-Portugol#1]
Não entendi muito bem os laços de repetição, você conseguiria me explicar melhor?

**Comment by GurgelAmaral** [comment]
Olá @karinaizo ! Amostras sobre a utilização de **laços de repetição** estão no meu repositório de [Portugol](https://github.com/GurgelAmaral/AVALIACAO-Portugol)

**Comment by GurgelAmaral** [comment]
Compreende?
